name: Build
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    uses: diepxuan/.github/.github/workflows/php-package-build.yml@main
