name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  test:
    permissions:
      contents: write
    uses: diepxuan/.github/.github/workflows/php-package-test.yml@main
